name: 6 Set Secrets

on: workflow_dispatch

env:
  AZURE_RG: OABoT_POC
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  CONTAINER_APP_NAME: oabotv3
  CONTAINER_APP_ENV:  env-c4gxnd5jx4mf6

jobs:
  deploy-container-app:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Create Container App Bot
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp secret set -n ${{ env.CONTAINER_APP_NAME }} -g ${{ env.AZURE_RG }} --secrets azure-openai-key=YourSecretValue
          az containerapp secret set -n ${{ env.CONTAINER_APP_NAME }} -g ${{ env.AZURE_RG }} --secrets microsoftappid=YourSecretValue
          az containerapp secret set -n ${{ env.CONTAINER_APP_NAME }} -g ${{ env.AZURE_RG }} --secrets microsoftapppassword=YourSecretValue
          az containerapp secret set -n ${{ env.CONTAINER_APP_NAME }} -g ${{ env.AZURE_RG }} --secrets search-index=YourSecretValue
          az containerapp secret set -n ${{ env.CONTAINER_APP_NAME }} -g ${{ env.AZURE_RG }} --secrets search-key=YourSecretValue

          
